/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carrossel: typeof import('./src/components/CurvedCarousel.vue')['default']
    CurvedCarousel: typeof import('./src/components/CurvedCarousel.vue')['default']
    Navigation: typeof import('./src/components/navigation.vue')['default']
    ProjectCard: typeof import('./src/components/projectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
