/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarouselProjects: typeof import('./src/components/carouselProjects.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    ProjectCard: typeof import('./src/components/projectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialIcons: typeof import('./src/components/socialIcons.vue')['default']
  }
}
